name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  go_version: 1.23
  GO111MODULE: on
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

jobs:
  Rosetta-Validation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: "3.9"

      - name: Install Docker Compose via Package Manager
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
        shell: bash

      - name: Verify Docker Compose Installation
        run: docker-compose --version
        shell: bash

      - name: Start a private ethereum network
        uses: ./.github/actions/geth
        id: geth

      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash

      - name: Get latest block from geth node
        run: |
          curl -X POST "http://127.0.0.1:8546" --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true],"id":1}'
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install web3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install web3==5.31.3
        shell: bash

      - name: deploy erc20 USDC
        run: .github/scripts/init_erc20.sh
        shell: bash

      - name: Get erc20 infos
        run: python .github/scripts/contract_infos.py
        shell: bash

      - name: Populate transactions
        run: python .github/scripts/populate_txns.py
        shell: bash

      - name: Start Rosetta Server
        run: .github/scripts/setup.sh
        shell: bash

      - name: Run Check:construction test
        run: .github/scripts/construction.sh
        shell: bash

      - name: Run Check:data test
        run: .github/scripts/cli.sh
        shell: bash

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          go-version: ${{ env.go_version }}
      - run: make test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          go-version: ${{ env.go_version }}
      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          args: --timeout 3m

  Check-License:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          version: latest
      - uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          go-version: ${{ env.go_version }}
      - run: make check-license

  Check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          version: latest
      - run: make check-format

  Salus:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          version: latest
      - run: make salus
