name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  go_version: 1.16
  GO111MODULE: on
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - run: make test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m

  Check-License:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          version: latest
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - run: make check-license

  Check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          version: latest
      - run: make check-format

  Salus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          version: latest
      - run: make salus

  